In [1]:
a = [1,2,3,4]
b = [2,3,4,5]

In [2]:
ab = []                        

for i in range(0, len(a)):
  ab.append(a[i]*b[i])

ab

[2, 6, 12, 20]

## Neden Numpy?

In [3]:
import numpy as np

In [4]:
a =  np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [5]:
a*b

array([ 5, 12, 21, 32])

## Numpy Array Olusturmak


In [6]:
np.array([3,6,7,1,9])

array([3, 6, 7, 1, 9])

In [7]:
a = np.array([1,2,3,4,5])

In [8]:
type(a)

numpy.ndarray

In [9]:
np.array([1,2,4,5.2,6.5],dtype=int)

array([1, 2, 4, 5, 6])

#### Sifirdan array olusturmak

In [10]:
np.zeros(7,dtype="int")

array([0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [12]:
np.arange(1,20,4)

array([ 1,  5,  9, 13, 17])

In [14]:
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [17]:
np.random.randint(0,10,(3,3))

array([[4, 9, 0],
       [4, 7, 5],
       [2, 3, 7]])

## Ozellikleri

-ndim
-shape
-size
-dtype

In [18]:
np.random.randint(10,size=10)

array([2, 6, 2, 4, 7, 7, 5, 6, 7, 9])

In [19]:
a = np.random.randint(10,size=10)

In [24]:
a.ndim

1

In [26]:
a.shape

(10,)

In [27]:
a.size

10

In [28]:
a.dtype

dtype('int64')

In [29]:
b = np.random.randint(0,10,(4,2))

In [23]:
b.ndim

2

In [30]:
b.shape

(4, 2)

In [31]:
b.size

8

In [32]:
b.dtype

dtype('int64')

## Yeniden sekillendirme - Reshaping

In [33]:
a = np.arange(1,10)

In [36]:
a.ndim

1

In [37]:
b = a.reshape((1,9))

In [38]:
b.ndim

2

In [39]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

## Concatenation

In [41]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [43]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [44]:
z = np.array([7,8,9])

In [45]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Iki boyut

In [46]:
a = np.array([[1,2,3], 
              [4,5,6]])

In [47]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

## Splitting

In [48]:
x = np.array([1,2,3,99,99,3,2,1])

In [49]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [50]:
a,b,c = np.split(x, [3,5])

In [51]:
a

array([1, 2, 3])

In [52]:
b

array([99, 99])

In [53]:
c

array([3, 2, 1])

## Sorting

In [56]:
v = np.array([2,1,4,3,5])

In [57]:
v

array([2, 1, 4, 3, 5])

In [58]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [59]:
v

array([2, 1, 4, 3, 5])

Iki Boyutu Arraylerde Siralama

In [60]:
m = np.random.normal(20,5, (3,3))

In [61]:
m

array([[17.77059994, 19.30368416, 23.25843795],
       [17.45009885, 16.44903323, 24.42416443],
       [21.63182535, 21.89214738, 18.95470251]])

In [66]:
np.sort(m,axis=0)

array([[16.44903323, 17.45009885, 21.89214738],
       [17.77059994, 19.30368416, 23.25843795],
       [18.95470251, 21.63182535, 24.42416443]])

In [67]:
np.sort(m,axis=1)

array([[17.77059994, 19.30368416, 23.25843795],
       [16.44903323, 17.45009885, 24.42416443],
       [18.95470251, 21.63182535, 21.89214738]])

## Indexing

In [68]:
a = np.random.randint(10, size = 10)
a

array([5, 9, 8, 7, 6, 8, 0, 5, 4, 8])

In [69]:
a[0]

5

In [70]:
a[-1]

8

In [71]:
a[0] = 100

a

In [73]:
m = np.random.randint(10, size = (3,5))
m

array([[5, 8, 0, 9, 0],
       [6, 5, 8, 1, 2],
       [4, 2, 4, 2, 6]])

In [74]:
m[0,0]

5

In [78]:
m[1, 4] = 99

In [79]:
m[1,4] = 2.2

In [81]:
m

array([[5, 8, 0, 9, 0],
       [6, 5, 8, 1, 2],
       [4, 2, 4, 2, 6]])

## Slicing

In [83]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [84]:
a[0:3]

array([20, 21, 22])

In [85]:
a[:3]

array([20, 21, 22])

In [86]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [87]:
a[1::2]

array([21, 23, 25, 27, 29])

In [88]:
a[0::3]

array([20, 23, 26, 29])

İki boyutlu Slice İslemleri

In [89]:
m = np.random.randint(10,size=(5,5))

In [90]:
m

array([[9, 9, 6, 0, 6],
       [0, 2, 5, 3, 1],
       [5, 3, 3, 2, 7],
       [9, 4, 3, 5, 2],
       [9, 6, 7, 1, 5]])

In [91]:
m[:,0]

array([9, 0, 5, 9, 9])

In [92]:
m[1,:]

array([0, 2, 5, 3, 1])

In [93]:
m[:2,0:3]

array([[9, 9, 6],
       [0, 2, 5]])

In [94]:
np.mean(a)

24.5

# PANDAS

In [96]:
import pandas as pd

In [97]:
pd.Series([10,76,1,2])

0    10
1    76
2     1
3     2
dtype: int64

In [98]:
seri = pd.Series([10,88,3,4,5])

In [99]:
type(seri)

pandas.core.series.Series

In [100]:
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

In [101]:
seri.ndim

1

In [102]:
seri.size

5

In [103]:
seri.dtype

dtype('int64')

In [104]:
seri.values

array([10, 88,  3,  4,  5])

In [105]:
seri.head(3)

0    10
1    88
2     3
dtype: int64

In [106]:
pd.Series([99,22,332,94,5], index = ["A","B","C","D","E"])

A     99
B     22
C    332
D     94
E      5
dtype: int64

## DataFrame

In [107]:
l = [1,2,39,67,90]

In [109]:
type(l)

list

In [111]:
pList = pd.DataFrame(l,columns=["value names"])

In [113]:
type(pList)

pandas.core.frame.DataFrame

In [114]:
import numpy as np
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [116]:
df = pd.DataFrame(m,columns=["var1","var2","var3"])

In [117]:
df.head(2)

var1  var2  var3
0     1     2     3
1     4     5     6

In [118]:
df.shape

(3, 3)

In [119]:
df.dtypes

var1    int64
var2    int64
var3    int64
dtype: object

In [120]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['var1', 'var2', 'var3'], dtype='object')]

In [121]:
df.ndim

2

In [124]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df

var1  var2  var3
0    21     4    26
1    21    21    22
2    29     4    14
3     1    19    21
4    29    24    18
5    24    10     1
6     9    13    11
7    19    13     5
8    12    12    24
9    14     9     8

In [125]:
df.loc[0:3]

var1  var2  var3
0    21     4    26
1    21    21    22
2    29     4    14
3     1    19    21

In [127]:
df.iloc[0:3]

var1  var2  var3
0    21     4    26
1    21    21    22
2    29     4    14

In [128]:
df.iloc[0:3]["var2"]

0     4
1    21
2     4
Name: var2, dtype: int64

In [129]:
df.loc[0:3]["var2"]

0     4
1    21
2     4
3    19
Name: var2, dtype: int64

In [130]:
df["var1"]

0    21
1    21
2    29
3     1
4    29
5    24
6     9
7    19
8    12
9    14
Name: var1, dtype: int64

In [133]:
df

var1  var2  var3
0    21     4    26
1    21    21    22
2    29     4    14
3     1    19    21
4    29    24    18
5    24    10     1
6     9    13    11
7    19    13     5
8    12    12    24
9    14     9     8

In [132]:
df[0:2][["var1","var2"]]

var1  var2
0    21     4
1    21    21

In [134]:
df.loc[0:3, "var3"]

0    26
1    22
2    14
3    21
Name: var3, dtype: int64

In [135]:
df[(df.var1 > 15 )]

var1  var2  var3
0    21     4    26
1    21    21    22
2    29     4    14
4    29    24    18
5    24    10     1
7    19    13     5

# Toplulaştırma ve Gruplama (Aggregation & Grouping)

In [136]:
import seaborn as sns

In [137]:
df = sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [138]:
df.shape

(1035, 6)

In [139]:
df.columns

Index(['method', 'number', 'orbital_period', 'mass', 'distance', 'year'], dtype='object')

In [143]:
df.mean()

/var/folders/gd/_bvnd5rx6mg73g6mcwl40c080000gn/T/ipykernel_3354/3698961737.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.mean()


number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

In [144]:
df["mass"].mean()

2.6381605847953233

In [145]:
df["mass"].count()

513

In [146]:
df["mass"].min()

0.0036

In [147]:
df["mass"].max()

25.0

In [148]:
df["mass"].std()

3.8186166509616046

In [152]:
df.describe().T

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

## Gruplama İslemleri

In [153]:
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'veri': [10,11,52,23,43,55]}, columns=['gruplar', 'veri'])
df

gruplar  veri
0       A    10
1       B    11
2       C    52
3       A    23
4       B    43
5       C    55

In [155]:
df.groupby("gruplar")

In [156]:
df.groupby("gruplar").mean()

veri
gruplar      
A        16.5
B        27.0
C        53.5

In [157]:
df.groupby("gruplar").sum()

veri
gruplar      
A          33
B          54
C         107

In [158]:
df = sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [159]:
df.tail()

method  number  orbital_period  mass  distance  year
1030  Transit       1        3.941507   NaN     172.0  2006
1031  Transit       1        2.615864   NaN     148.0  2007
1032  Transit       1        3.191524   NaN     174.0  2007
1033  Transit       1        4.125083   NaN     293.0  2008
1034  Transit       1        4.187757   NaN     260.0  2008

In [160]:
df.groupby("method")

In [161]:
df.groupby("method")["orbital_period"].mean()

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [164]:
df.groupby("method")["orbital_period"].describe()

count           mean            std  \
method                                                               
Astrometry                       2.0     631.180000     544.217663   
Eclipse Timing Variations        9.0    4751.644444    2499.130945   
Imaging                         12.0  118247.737500  213978.177277   
Microlensing                     7.0    3153.571429    1113.166333   
Orbital Brightness Modulation    3.0       0.709307       0.725493   
Pulsar Timing                    5.0    7343.021201   16313.265573   
Pulsation Timing Variations      1.0    1170.000000            NaN   
Radial Velocity                553.0     823.354680    1454.926210   
Transit                        397.0      21.102073      46.185893   
Transit Timing Variations        3.0      79.783500      71.599884   

                                       min          25%           50%  \
method                                                                  
Astrometry                      246.360000   438.770000    631.180000   
Eclipse Timing Variations      1916.250000  2900.000000   4343.500000   
Imaging                        4639.150000  8343.900000  27500.000000   
Microlensing                   1825.000000  2375.000000   3300.000000   
Orbital Brightness Modulation     0.240104     0.291496      0.342887   
Pulsar Timing                     0.090706    25.262000     66.541900   
Pulsation Timing Variations    1170.000000  1170.000000   1170.000000   
Radial Velocity                   0.736540    38.021000    360.200000   
Transit                           0.355000     3.160630      5.714932   
Transit Timing Variations        22.339500    39.675250     57.011000   

                                        75%            max  
method                                                      
Astrometry                       823.590000    1016.000000  
Eclipse Timing Variations       5767.000000   10220.000000  
Imaging                        94250.000000  730000.000000  
Microlensing                    3550.000000    5100.000000  
Orbital Brightness Modulation      0.943908       1.544929  
Pulsar Timing                     98.211400   36525.000000  
Pulsation Timing Variations     1170.000000    1170.000000  
Radial Velocity                  982.000000   17337.500000  
Transit                           16.145700     331.600590  
Transit Timing Variations        108.505500     160.000000